version: '3.8'
services:
  postgres:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - imarika_network

  migrations:
    build: ./db/migrations
    working_dir: /app/migrations
    volumes:
      - ./db/migrations:/app/migrations
    env_file:
      - db/.env
    depends_on:
      postgres:
        condition: service_healthy  # Ensures migrations run only after Postgres is ready
    command: >
      sh -c "sleep 5 && alembic -c /app/migrations/alembic.ini upgrade head"
    networks:
      - imarika_network

  # chroma db
  chroma:
    build: ./db/chroma
    ports:
      - "5433:8000"
    volumes:
      - ./db/chroma/data:/chroma/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - imarika_network

  ws_server:
    build: .               # Uses the root-level Dockerfile
    command: uvicorn server.ws_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      chroma:
        condition: service_started
    restart: always
    networks:
      - imarika_network

  streamlit:
    build: .
    command: streamlit run app/main.py --server.enableCORS false
    ports:
      - "8501:8501"
    depends_on:
      - ws_server
    restart: always
    networks:
      - imarika_network

  whatsapp_api:
    build:
      context: .
    command: uvicorn server.whatsapp_api:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - migrations
      - chroma
    networks:
      - imarika_network


networks:
  imarika_network:
    driver: bridge

volumes:
  postgres_data:
  chroma_data: